export default {
  rules: [
    {
      lamaUsaha: '0 - 2',
      jumlahPekerja: '< 10',
      omzet: '< 1',
      jumlahAset: '< 5',
    },
    {
      lamaUsaha: '3 - 7',
      jumlahPekerja: '10 - 19',
      omzet: '1 - 2',
      jumlahAset: '5 - 6',
    },
    {
      lamaUsaha: '> 7',
      jumlahPekerja: '20 - 30',
      omzet: '3 - 5',
      jumlahAset: '7 - 10',
    },
  ],
  parameters: [
    {
      name: 'Lama Usaha',
      criterias: ['0 - 2', '3 - 7', '> 7'],
    },
    {
      name: 'Jumlah Pekerja',
      criterias: ['< 10', '10 - 19', '20 - 30'],
    },
    {
      name: 'Omzet',
      criterias: ['< 1', '1 - 2', '3 - 5'],
    },
    {
      name: 'Jumlah Aset',
      criterias: ['< 5', '5 - 6', '7 - 10'],
    },
  ],
  datasets: [
    {
      namaUKM: 'Sanggar Azalea',
      lamaUsaha: '2',
      jumlahPekerja: '14',
      omzet: '3',
      jumlahAset: '2',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Kedurus Sejahtera',
      lamaUsaha: '6',
      jumlahPekerja: '7',
      omzet: '5',
      jumlahAset: '4',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Rapi Ayu Handycraft',
      lamaUsaha: '4',
      jumlahPekerja: '16',
      omzet: '1',
      jumlahAset: '10',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Jaya Komputer',
      lamaUsaha: '2',
      jumlahPekerja: '9',
      omzet: '2',
      jumlahAset: '2',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Purnama',
      lamaUsaha: '1',
      jumlahPekerja: '9',
      omzet: '5',
      jumlahAset: '4',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Kencana Craft',
      lamaUsaha: '3',
      jumlahPekerja: '22',
      omzet: '2',
      jumlahAset: '1',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'V-Tri Accessories',
      lamaUsaha: '4',
      jumlahPekerja: '14',
      omzet: '2',
      jumlahAset: '3',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Maju Jaya Sablon',
      lamaUsaha: '5',
      jumlahPekerja: '1',
      omzet: '3',
      jumlahAset: '2',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Batik Semanggi',
      lamaUsaha: '6',
      jumlahPekerja: '1',
      omzet: '2',
      jumlahAset: '3',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Sunrise Picture',
      lamaUsaha: '7',
      jumlahPekerja: '13',
      omzet: '5',
      jumlahAset: '10',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Mitra Mandiri',
      lamaUsaha: '4',
      jumlahPekerja: '3',
      omzet: '3',
      jumlahAset: '6',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Liana',
      lamaUsaha: '0',
      jumlahPekerja: '15',
      omzet: '3',
      jumlahAset: '6',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Madekan',
      lamaUsaha: '7',
      jumlahPekerja: '15',
      omzet: '3',
      jumlahAset: '8',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Temuwati',
      lamaUsaha: '2',
      jumlahPekerja: '26',
      omzet: '1',
      jumlahAset: '8',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Eva Nur Fadillah',
      lamaUsaha: '5',
      jumlahPekerja: '23',
      omzet: '3',
      jumlahAset: '10',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Sri Sulatiningsih',
      lamaUsaha: '3',
      jumlahPekerja: '18',
      omzet: '5',
      jumlahAset: '7',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Warna Ayu',
      lamaUsaha: '7',
      jumlahPekerja: '20',
      omzet: '3',
      jumlahAset: '6',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Ukm Jasierah',
      lamaUsaha: '3',
      jumlahPekerja: '2',
      omzet: '2',
      jumlahAset: '9',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Nurul',
      lamaUsaha: '6',
      jumlahPekerja: '16',
      omzet: '5',
      jumlahAset: '7',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Pujiati',
      lamaUsaha: '0',
      jumlahPekerja: '24',
      omzet: '3',
      jumlahAset: '1',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Indrayani',
      lamaUsaha: '2',
      jumlahPekerja: '18',
      omzet: '1',
      jumlahAset: '8',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Ksm Kurma',
      lamaUsaha: '0',
      jumlahPekerja: '5',
      omzet: '2',
      jumlahAset: '5',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Ukm Danadipa Etnik',
      lamaUsaha: '3',
      jumlahPekerja: '10',
      omzet: '1',
      jumlahAset: '1',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Ukm Enfina',
      lamaUsaha: '3',
      jumlahPekerja: '25',
      omzet: '4',
      jumlahAset: '6',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Ksm Lezat',
      lamaUsaha: '2',
      jumlahPekerja: '4',
      omzet: '1',
      jumlahAset: '1',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Andyni Collection',
      lamaUsaha: '7',
      jumlahPekerja: '30',
      omzet: '1',
      jumlahAset: '3',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Ananda Collection',
      lamaUsaha: '6',
      jumlahPekerja: '3',
      omzet: '4',
      jumlahAset: '7',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Umk Rumpun Bambu',
      lamaUsaha: '5',
      jumlahPekerja: '19',
      omzet: '5',
      jumlahAset: '2',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Umk Flamboyan',
      lamaUsaha: '4',
      jumlahPekerja: '25',
      omzet: '2',
      jumlahAset: '4',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Umk Tandu A.W',
      lamaUsaha: '3',
      jumlahPekerja: '3',
      omzet: '2',
      jumlahAset: '4',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Umk Prayogi',
      lamaUsaha: '7',
      jumlahPekerja: '19',
      omzet: '5',
      jumlahAset: '3',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Umk Dian Collection',
      lamaUsaha: '1',
      jumlahPekerja: '24',
      omzet: '5',
      jumlahAset: '7',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Kelompok Tani',
      lamaUsaha: '4',
      jumlahPekerja: '20',
      omzet: '4',
      jumlahAset: '1',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Umi Hanik',
      lamaUsaha: '2',
      jumlahPekerja: '12',
      omzet: '4',
      jumlahAset: '4',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Lilik Yulfa',
      lamaUsaha: '7',
      jumlahPekerja: '29',
      omzet: '5',
      jumlahAset: '2',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Titik Suprihatin',
      lamaUsaha: '5',
      jumlahPekerja: '3',
      omzet: '1',
      jumlahAset: '2',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Tutik Jaslikan',
      lamaUsaha: '5',
      jumlahPekerja: '6',
      omzet: '1',
      jumlahAset: '6',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Subaun',
      lamaUsaha: '4',
      jumlahPekerja: '23',
      omzet: '5',
      jumlahAset: '6',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Mekan',
      lamaUsaha: '7',
      jumlahPekerja: '17',
      omzet: '2',
      jumlahAset: '7',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Ksm Budaya 4',
      lamaUsaha: '1',
      jumlahPekerja: '21',
      omzet: '2',
      jumlahAset: '8',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Umk Warga Mandiri',
      lamaUsaha: '4',
      jumlahPekerja: '1',
      omzet: '2',
      jumlahAset: '8',
      keputusan: 'YA',
    },
    {
      namaUKM: 'Ksm Kreatif & Koi',
      lamaUsaha: '7',
      jumlahPekerja: '10',
      omzet: '5',
      jumlahAset: '4',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Sri Lasmini Budiono',
      lamaUsaha: '1',
      jumlahPekerja: '30',
      omzet: '1',
      jumlahAset: '6',
      keputusan: 'TUNDA',
    },
    {
      namaUKM: 'Umk Sayu Sejahtera',
      lamaUsaha: '5',
      jumlahPekerja: '8',
      omzet: '5',
      jumlahAset: '3',
      keputusan: 'TIDAK',
    },
    {
      namaUKM: 'Windu Collection',
      lamaUsaha: '2',
      jumlahPekerja: '26',
      omzet: '2',
      jumlahAset: '9',
      keputusan: 'YA',
    },
  ],
};
